services:
  frontend:
    build: 
      dockerfile: Dockerfile
      context: front-end
    ports:
      - "4200:4200"
    depends_on:
      - backend
  backend:
    build: 
      dockerfile: Dockerfile
      context: bug-bounty-backend
    ports:
      - "8080:8080"
  # TODO: Add database service in here
  #   depends_on:
  #     - database
  # database:
  # bla bla bla