services:
  database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 20

  backend:
    build: 
      dockerfile: Dockerfile
      context: bug-bounty-backend
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy

  frontend:
    build: 
      dockerfile: Dockerfile
      context: front-end
    ports:
      - "4200:4200"
    depends_on:
      - backend
